on: push
name: Test and deploy to Firebase on push
jobs:
  installFunctionsDependencies:
    name: Install functions dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install functions dependencies
      uses: actions/npm@master
      with:
        args: --prefix ./functions install
    - name: Lint functions
      uses: actions/npm@master
      with:
        args: --prefix ./functions run lint
    - name: Filter for master branch
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Deploy Firebase Functions
      uses: pizzafox/firebase-action@master
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: zero-width-shortener
      with:
        args: deploy --only functions
    - name: Deploy Firebase Firestore
      uses: pizzafox/firebase-action@master
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: zero-width-shortener
      with:
        args: deploy --only firestore
